name: release

on:
  push:
    tags:
      - "*"

jobs:
  npm:
    name: Publish to NPM
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish
